repo: minvws/nl-covid19-notification-app-website

collections:
  statements:
    output: true
    permalink: /:path
  questions:
    output: true
    permalink: /:path

sass:
  sass_dir: css

# needed for travis CI
exclude: [vendor]
